// <auto-generated />
using System;
using MarketService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20260320170436_TradingPets")]
    partial class TradingPets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketService.Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BuyerTraderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("BuyerTraderId");

                    b.HasIndex("ListingId", "Status");

                    b.ToTable("PetListingBids", (string)null);
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaselineDesirability")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("LifespanYears")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MaintenanceCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PetBreeds", (string)null);
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("ReferencePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ItemId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            ItemId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Equity",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsTradable = true,
                            Name = "Acme Beverage Co",
                            ReferencePrice = 100m,
                            Symbol = "ABC"
                        },
                        new
                        {
                            ItemId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Equity",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsTradable = true,
                            Name = "Xylophone Yield Zone",
                            ReferencePrice = 80m,
                            Symbol = "XYZ"
                        });
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AskingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellerTraderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SellerTraderId");

                    b.HasIndex("PetId", "WithdrawnAt");

                    b.ToTable("PetListings", (string)null);
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Correlation")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CounterpartyDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("CounterpartyTraderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("TraderId", "CreatedAt");

                    b.ToTable("PetNotifications", (string)null);
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("MarketService.Domain.Entities.OrderMatchAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("MatchPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MatchQuantity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("MatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SellOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditId");

                    b.ToTable("OrderMatchAudits", (string)null);
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AgeYears")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("BreedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentDesirability")
                        .HasColumnType("int");

                    b.Property<decimal>("Health")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnerTraderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("OwnerTraderId");

                    b.ToTable("Pets", (string)null);
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Supply", b =>
                {
                    b.Property<Guid>("BreedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RemainingCount")
                        .HasColumnType("int");

                    b.HasKey("BreedId");

                    b.ToTable("PetBreedSupply", (string)null);
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerTraderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SellerTraderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuyerTraderId");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("ListingId");

                    b.HasIndex("PetId");

                    b.HasIndex("SellerTraderId");

                    b.ToTable("PetTrades", (string)null);
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Trader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AvailableCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("LockedCash")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId");

                    b.ToTable("PetTraders", (string)null);
                });

            modelBuilder.Entity("MarketService.Infrastructure.Persistence.DemoAccountRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("CashAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId");

                    b.ToTable("DemoAccounts", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-1",
                            CashAvailable = 250000m,
                            DisplayName = "Buyer One",
                            Email = "user1@example.com"
                        },
                        new
                        {
                            UserId = "user-2",
                            CashAvailable = 150000m,
                            DisplayName = "Seller Two",
                            Email = "user2@example.com"
                        },
                        new
                        {
                            UserId = "user-3",
                            CashAvailable = 50000m,
                            DisplayName = "Observer Three",
                            Email = "user3@example.com"
                        });
                });

            modelBuilder.Entity("MarketService.Infrastructure.Persistence.DemoHoldingRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("UserId", "Symbol");

                    b.ToTable("DemoHoldings", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-1",
                            Symbol = "ABC",
                            Quantity = 10
                        },
                        new
                        {
                            UserId = "user-2",
                            Symbol = "ABC",
                            Quantity = 200
                        },
                        new
                        {
                            UserId = "user-3",
                            Symbol = "XYZ",
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Bid", b =>
                {
                    b.HasOne("MarketService.Domain.Entities.Trader", "Buyer")
                        .WithMany("BidsAsBuyer")
                        .HasForeignKey("BuyerTraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketService.Domain.Entities.Listing", "Listing")
                        .WithMany("Bids")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Listing", b =>
                {
                    b.HasOne("MarketService.Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketService.Domain.Entities.Trader", "Seller")
                        .WithMany("ListingsAsSeller")
                        .HasForeignKey("SellerTraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MarketService.Domain.Entities.Trader", "Trader")
                        .WithMany("Notifications")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Pet", b =>
                {
                    b.HasOne("MarketService.Domain.Entities.Breed", "Breed")
                        .WithMany("Pets")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketService.Domain.Entities.Trader", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerTraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Supply", b =>
                {
                    b.HasOne("MarketService.Domain.Entities.Breed", "Breed")
                        .WithOne("Supply")
                        .HasForeignKey("MarketService.Domain.Entities.Supply", "BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Trade", b =>
                {
                    b.HasOne("MarketService.Domain.Entities.Trader", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerTraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketService.Domain.Entities.Listing", "Listing")
                        .WithMany("Trades")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketService.Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketService.Domain.Entities.Trader", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerTraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("Pet");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("MarketService.Infrastructure.Persistence.DemoHoldingRecord", b =>
                {
                    b.HasOne("MarketService.Infrastructure.Persistence.DemoAccountRecord", null)
                        .WithMany("Holdings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Breed", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Listing", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Trader", b =>
                {
                    b.Navigation("BidsAsBuyer");

                    b.Navigation("ListingsAsSeller");

                    b.Navigation("Notifications");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("MarketService.Infrastructure.Persistence.DemoAccountRecord", b =>
                {
                    b.Navigation("Holdings");
                });
#pragma warning restore 612, 618
        }
    }
}
