// <auto-generated />
using System;
using MarketService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    partial class MarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketService.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("ReferencePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ItemId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            ItemId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Equity",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsTradable = true,
                            Name = "Acme Beverage Co",
                            ReferencePrice = 100m,
                            Symbol = "ABC"
                        },
                        new
                        {
                            ItemId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Equity",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsTradable = true,
                            Name = "Xylophone Yield Zone",
                            ReferencePrice = 80m,
                            Symbol = "XYZ"
                        });
                });

            modelBuilder.Entity("MarketService.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("MarketService.Domain.Entities.OrderMatchAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("MatchPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MatchQuantity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("MatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SellOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditId");

                    b.ToTable("OrderMatchAudits", (string)null);
                });

            modelBuilder.Entity("MarketService.Infrastructure.Persistence.DemoAccountRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("CashAvailable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId");

                    b.ToTable("DemoAccounts", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-1",
                            CashAvailable = 250000m,
                            DisplayName = "Buyer One",
                            Email = "user1@example.com"
                        },
                        new
                        {
                            UserId = "user-2",
                            CashAvailable = 150000m,
                            DisplayName = "Seller Two",
                            Email = "user2@example.com"
                        },
                        new
                        {
                            UserId = "user-3",
                            CashAvailable = 50000m,
                            DisplayName = "Observer Three",
                            Email = "user3@example.com"
                        });
                });

            modelBuilder.Entity("MarketService.Infrastructure.Persistence.DemoHoldingRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("UserId", "Symbol");

                    b.ToTable("DemoHoldings", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-1",
                            Symbol = "ABC",
                            Quantity = 10
                        },
                        new
                        {
                            UserId = "user-2",
                            Symbol = "ABC",
                            Quantity = 200
                        },
                        new
                        {
                            UserId = "user-3",
                            Symbol = "XYZ",
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("MarketService.Infrastructure.Persistence.DemoHoldingRecord", b =>
                {
                    b.HasOne("MarketService.Infrastructure.Persistence.DemoAccountRecord", null)
                        .WithMany("Holdings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketService.Infrastructure.Persistence.DemoAccountRecord", b =>
                {
                    b.Navigation("Holdings");
                });
#pragma warning restore 612, 618
        }
    }
}
