<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MarketService.Domain\MarketService.Domain.csproj" />
    <ProjectReference Include="..\MarketService.Application\MarketService.Application.csproj" />
    <ProjectReference Include="..\..\..\..\..\libs\building-blocks\messaging\src\Trading.Messaging\Trading.Messaging.csproj" />
    <ProjectReference Include="..\..\..\..\..\libs\contracts\events\src\Trading.Contracts.Events\Trading.Contracts.Events.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
