namespace MarketService.Application.Accounts;

/// <summary>
/// Human-facing labels for traders backed by demo accounts: prefer a real display name, then email.
/// Auto-generated <c>Trader {suffix}</c> labels count as missing so email can be shown instead.
/// </summary>
public static class AccountPublicDisplayName
{
    public static bool IsAutoGeneratedTraderLabel(string? displayName)
    {
        if (string.IsNullOrWhiteSpace(displayName))
        {
            return true;
        }

        var t = displayName.Trim();
        const string prefix = "Trader ";
        if (t.Length <= prefix.Length || !t.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        var suffix = t.AsSpan(prefix.Length).Trim();
        if (suffix.IsEmpty || suffix.Length > 16)
        {
            return true;
        }

        foreach (var c in suffix)
        {
            if (!char.IsLetterOrDigit(c))
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>
    /// For a row in <c>DemoAccounts</c> (always linked to an external user id).
    /// </summary>
    public static string ForDemoAccount(string accountDisplayName, string? accountEmail) =>
        ForLinkedExternalUser(accountDisplayName, accountDisplayName, accountEmail);

    /// <summary>
    /// When the trader may be linked to a demo account, prefer account display name, then email, then trader display name.
    /// </summary>
    public static string ForLinkedExternalUser(
        string traderDisplayName,
        string? accountDisplayName,
        string? accountEmail)
    {
        var acctDn = (accountDisplayName ?? "").Trim();
        var acctEm = (accountEmail ?? "").Trim();
        if (acctDn.Length > 0 && !IsAutoGeneratedTraderLabel(acctDn))
        {
            return acctDn;
        }

        if (acctEm.Length > 0)
        {
            return acctEm;
        }

        if (acctDn.Length > 0)
        {
            return acctDn;
        }

        var td = (traderDisplayName ?? "").Trim();
        return td.Length > 0 ? td : "Trader";
    }

    public static string ForUnlinkedTrader(string traderDisplayName)
    {
        var td = (traderDisplayName ?? "").Trim();
        return td.Length > 0 ? td : "Trader";
    }
}
